pipeline:
  clone:
    disabled: true
  stages:
    - runtime: shell
      id: k8s-rolling-deploy_1
      service:
        id: RemoteService2
        ref: remoteService2
      action:
        uses: k8s_rolling_k8
